export const data = [
    {
        company: 'Flock, LLC.',
        date: 'Sep, 2023 – Present',
        status: 'Project Completed Successfully',
        title: 'Flock(Feeling Management)',
        type: 'React Native(Android/iOS) Mobile Application',
        client: '<b>Jennifer Wilson</b>(United States): Teacher of Kalani High School(Hawaii)',
        role: 'React Native, Backend(API) Developer',
        technology: '<b>React Native</b>, Redux, Hook, Saga, React Chart,\nFirebase Firestore Database, Firebase Could Function,\nGoogle Map Api Integration, GPS Tracking',
        images: [
            { src: '0001.png' },
            { src: '0002.png' },
            { src: '0003.png' },
            { src: '0004.png' },
        ],
        appstore: '',
        playstore: '',
        youtube: '',
        website: '',
        other: '* Challenge: Setting many markers in google map\n* Design: From Scratch',
    },
    {
        company: 'Qalorie, Inc.',
        date: 'Jan, 2021 – May, 2022',
        status: 'Project Completed Successfully',
        title: 'Qalorie(Calorie Measurement)',
        type: 'React/React Native(Android/iOS) Web, Mobile Application',
        client: '<b>Rafael Rivera</b>(Puerto Rico): CEO at Qalorie, Inc.',
        role: 'Project Manager, Web, Mobile, Backend(API) Developer',
        technology: '<b>React Native</b>, Redux, Hook, Saga,\nNode.js(Backend), MongoDB(Database), AWS S3 Buckets,\nSocial Authentication(Facebook, Apple, Google, Email) using Firebase,\nVideo & Voice Call using <b>CometChat platform</b>, Live Chat, Push Noticiation,\nSocial Media Feature(Multiple Image, Videos Posting and Comment, Like, User Following),\nPayment Gateway Integration(PayPal, Stripe)\nPublishing on AppStore, PlayStore',
        images: [
            { src: '0005.png' },
            { src: '0009.png' },
            { src: '0007.png' },
            { src: '0010.png' },
            { src: '0008.png' },
            { src: '0011.png' },
        ],
        appstore: 'https://apps.apple.com/us/app/qalorie/id1538149091',
        playstore: 'https://play.google.com/store/apps/details?id=com.qalorieapp&hl=en_US',
        youtube: 'https://youtu.be/mUx_bmXiUgs',
        website: 'https://qalorie.com',
        other: '* Challenge: Editing and Trimming Videos for Sharing on Social Media\n* Design: Figma, Invision',
    },
    {
        company: '',
        date: '',
        status: '',
        title: 'Qalorie(Calorie Measurement)',
        type: 'Node(ExpressJS)/MongoDB/AWS(S3 Buckets)',
        client: '<b>Rafael Rivera</b>(Puerto Rico): CEO at Qalorie, Inc.',
        role: 'Project Manager, Web, Mobile, Backend(API) Developer',
        technology: '<b>Node(ExpressJS)</b>, MongoDB(Database), AWS S3 Buckets',
        images: [
            { src: '0060.png' },
            { src: '0061.png' },
            { src: '0062.png' },
        ],
        appstore: '',
        playstore: '',
        youtube: '',
        website: '',
        other: '',
    },
    {
        company: 'Borw, Ltd.',
        date: 'Jul, 2019 – Feb, 2020',
        status: 'Project Completed Successfully',
        title: 'Borw(Circular Fashion, Buy & Sell)',
        type: 'React Native(Android/iOS) Mobile Application',
        client: '<b>Eleftheria Panagiotopoulou</b>(United Kingdom): CEO & Founder at Borw, Lecturer at Oxford Business College & Greenwich University, Sustainable Fashion Addict',
        role: 'Mobile Application Developer',
        technology: '<b>React Native</b>, Redux,\nFirebase Realtime Database, Firebase Cloud Function,\nSocial Authentication(Facebook, Apple, Google, Email) using Firebase,\nSocial Media Feature(Multiple Products Posting and Comment, Like, User Following),\n<b>Payment Gateway Integration</b>(PayPal, Bank Authorization),\nMulti-Language Implement(RTL/LTR) using i18n, Localization',
        images: [
            { src: '0017.png' },
            { src: '0018.png' },
            { src: '0019.png' },
            { src: '0013.png' },
            { src: '0020.png' },
            { src: '0016.png' },
        ],
        appstore: 'https://apps.apple.com/ca/app/borw/id1504578577',
        playstore: 'https://play.google.com/store/apps/details?id=com.borw',
        youtube: 'https://youtu.be/zFQFFhuZhcY',
        website: 'https://borw.app',
        other: '* Fashion apps often require handling and displaying images\n&emsp;&emsp;(Libraries: React Native Image, FastImage, and ImagePicker)\n* Share products with their social media accounts\n&emsp;&emsp;(Libraries: react-native-share and reacct-native-fbsdk)',
    },
    {
        company: 'Amdocs, Ltd.',
        date: 'Jan, 2019 – Mar, 2019',
        status: 'Project Completed Successfully',
        title: 'GoFit(Fitness, Gym & Workout)',
        type: 'React Native(Expo) Mobile Application',
        client: '<b>Rabia Abu Hanna</b>(Israel): Software Development Team Lead at Amdocs',
        role: 'React Native Developer',
        technology: '<b>React Native(Expo)</b>, Redux,\nFirebase Firestore, Database, Firebase Cloud Function,\nScheduling using Calendar, Unity Video Embeding,\nMulti-Language Implement(<b>RTL/LTR</b>) using i18n, Localization,\nSynchronizing with Bluetooth Watch(Apple Watch, Samsung Watch),\nFirebase Authentication, OAuth, or JWT(JSON Web Tokens),\nDark & Light Theme',
        images: [
            { src: '0023.png' },
            { src: '0021.png' },
            { src: '0024.png' },
            { src: '0022.png' },
        ],
        appstore: 'https://apps.apple.com/us/app/gofit-weight-loss-walking/id1460688355',
        playstore: 'https://play.google.com/store/apps/details?id=com.m4pmedia.gofit_walking',
        youtube: 'https://youtu.be/JS75-G-qFIs',
        website: '',
        other: '* Design: Sketch\n* Project Management: Hubstaff, Github'
    },
    {
        company: 'Crave Retail, Inc.',
        date: 'May, 2020 – Mar, 2021',
        status: 'Project Completed Successfully',
        title: 'HouseSigma/Brokier(Real Estates)',
        type: 'React(Next)/React Native(Expo)/PHP(Laravel)/MySQL',
        client: '<b>Amirghassemi Benhnam</b>(Canada): CTO at Crave Retail, Inc.',
        role: 'Project Manager, Full Stack Developer',
        technology: '<b>React Native(Expo)</b>, Redux, PHP, Laravel, MySQL,\nThird Party Api Integration using Axios,\nGoogle Analytics Implement\n(Libraries: react-native-firebase/analytics)',
        images: [
            { src: '0025.png' },
            { src: '0026.png' },
            { src: '0027.png' },
            { src: '0028.png' },
            { src: '0029.png' },
        ],
        appstore: 'https://apps.apple.com/ca/app/housesigma-canada-real-estate/id1255490256',
        playstore: 'https://play.google.com/store/apps/details?id=com.housesigma.android&hl=en_US&gl=US',
        youtube: 'https://youtu.be/lz95cwVvB5I',
        website: 'https://housesigma.com',
        other: '* Challenge: Google Map Clustering, Google Maps Markers with extensive\n&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;positions(Libraries: react-native-maps),\n&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;MySQL Indexing, Optimizing Database\n* Design: Figma\n* Project Management: Zira, Bitbucket',
    },
    {
        company: 'Romanian Food & Beverage, Ltd.',
        date: 'May, 2020 – Sep, 2020',
        status: 'Frontend Part Completed Successfully',
        title: 'FoodNet(Restaurant, Food Delivery, Recipe)',
        type: 'React Native/Ionic(Angular)',
        client: '<b>Iqbal Hossain</b>(Romania): COO at Romanian Food & Beverage, Ltd.',
        role: 'Frontend(Mobile Application) Developer',
        technology: '<b>React Native</b>, Redux, Hooks, Typescript,\n<b>Third Party Api Integration for Food Recipe & Ingredients</b>,\nPush Notification using Firebase Cloud Messaging\n&emsp;(Libraries: react-native-firebase/messaging),\nMulti-Language, Multi-Payment Gateway Integration\n&emsp;(Libraries: i18n, react-localization, @stripe/stripe-react-native,\n&emsp;react-native-paypal)',
        images: [
            { src: '0045.png' },
            { src: '0047.png' },
            { src: '0046.png' },
            { src: '0048.png' },
            { src: '0049.png' },
        ],
        appstore: 'https://apps.apple.com/us/app/food-network-kitchen/id399072152',
        playstore: 'https://play.google.com/store/apps/details?id=com.scripps.android.foodnetwork&hl=en_US',
        youtube: 'https://youtu.be/XDGSIJ3WguM',
        website: '',
        other: '* Design: Invision\n* Project Management: Hubstaff, GitLab, Slack',
    },
    {
        company: 'Technovier, Inc.',
        date: 'Sep, 2020 – Nov, 2020',
        status: 'Project Completed Successfully',
        title: 'Paksa/Noon(Online Shopping)',
        type: 'React Native(Android/iOS) Mobile Application',
        client: '<b>Khawaja Minhal Hassan</b>(Pakistan): CEO at Technovier, Inc.',
        role: 'Project Team Leader, Frontend Developer',
        technology: '<b>React Native</b>, Redux, Hooks, Python(Django), PostgreSQL,\nPush Notification using Firebase Cloud Messaging,\nMulti-Language, Multi-Payment Gateway Integration,\nProducts, Collection Management, Shopify API Integration using Axios.',
        images: [
            { src: '0050.png' },
            { src: '0053.png' },
            { src: '0051.png' },
            { src: '0052.png' },
            { src: '0054.png' },
            { src: '0055.png' },
        ],
        appstore: 'https://apps.apple.com/us/app/noon-shopping-%D9%86%D9%88%D9%86-%D9%84%D9%84%D8%AA%D8%B3%D9%88%D9%82/id1269038866 ',
        playstore: 'https://play.google.com/store/apps/details?id=com.noon.buyerapp&hl=en_US&gl=US',
        youtube: 'https://youtu.be/7zK89HbPaz4',
        website: '',
        other: '* Design: XD',
    },
];