export const data = [
    {
        category: 'mobile',
        company: 'Flock, LLC.',
        logo: 'flock.png',
        date: 'Sep, 2023 – Present',
        status: 'On-Going Project',
        title: 'Flock(Feeling Management)',
        type: 'React Native(Android/iOS) Mobile Application',
        avatar: 'jennifer.png',
        client: '<b>Jennifer Wilson</b> (United States)\nTeacher of Kalani High School(Hawaii)',
        review: {
            rating: 5,
            recommendation: "&emsp;\"I highly recommend Silas!! He is in constant communication with me. He has had to make many many changes for me and he does so easily. I showed him pictures of what I wanted and he can make anything that you give to him. Due to the language difference, I learned that he takes things literal, and once I figured that out and was able to be more clear about what I wanted he showed up perfect. I am very impressed with all the things that he has be able to do, from counting people, to maps, to analytics, and in a short amount of time. I will be working with him again on my next project!! I trust him and you won't be sorry. He is a hard worker and will figure out anything that you need.\""
        },
        role: 'React Native, Backend(API) Developer',
        technology: '<b>React Native</b>, Redux, Hook, Saga, React Chart,\nFirebase Firestore Database, Firebase Could Function,\nGoogle Map Api Integration, <b>GPS Tracking</b>, Google Analytics',
        icons: [
            'reactnative.png',
            'redux.png',
            'firebase.png',
            'googlemap.png',
            'gps.png',
        ],
        images: [
            { src: 'flock/1.png' },
            { src: 'flock/2.png' },
            { src: 'flock/3.png' },
            { src: 'flock/4.png' },
        ],
        appstore: '',
        playstore: '',
        youtube: '',
        website: '',
        other: '* Challenge: Setting many markers in google map\n* Design: From Scratch',
    },
    {
        category: 'mobile',
        company: 'Qalorie, Inc.',
        logo: 'qalorie.webp',
        date: 'Jan, 2021 – May, 2022',
        status: 'Project Completed Successfully',
        title: 'Qalorie(Calorie Measurement)',
        type: 'React/React Native(Android/iOS) Web, Mobile Application',
        avatar: 'rafael.png',
        client: '<b>Rafael Rivera</b> (Puerto Rico)\nCEO at Qalorie, Inc.',
        review: {
            rating: 5,
            recommendation: "&emsp;\"I had the pleasure of working with Silas on our recent our project, and the experience exceeded our expectations in every way. From start to finish, Silas demonstrated a high level of professionalism, technical expertise, and commitment to delivering a top-notch product.\""
        },
        role: 'Project Manager, Web, Mobile, Backend(API) Developer',
        technology: '<b>React Native</b>, Redux, Hook, Saga,\nNode.js(Backend), MongoDB(Database), AWS S3 Buckets,\nSocial Authentication(Facebook, Apple, Google, Email) using Firebase,\nVideo & Voice Call using <b>CometChat platform</b>, Live Chat,\nPush Noticiation, Google Analytics, Appsflyer Integration,\nSocial Media Feature(Multiple Image, Videos Posting and Comment, Like, User Following),\nPayment Gateway Integration(PayPal, Stripe)\nPublishing on AppStore, PlayStore',
        icons: [
            'reactnative.png',
            'redux.png',
            'saga.png',
            'android.png',
            'ios.png',
            'firebase.png',
            'cometchat.png',
        ],
        images: [
            { src: 'qalorie/1.png' },
            { src: 'qalorie/5.png' },
            { src: 'qalorie/3.png' },
            { src: 'qalorie/6.png' },
            { src: 'qalorie/4.png' },
            { src: 'qalorie/7.png' },
        ],
        appstore: 'https://apps.apple.com/us/app/qalorie/id1538149091',
        playstore: 'https://play.google.com/store/apps/details?id=com.qalorieapp&hl=en_US',
        youtube: 'https://youtu.be/mUx_bmXiUgs',
        website: 'https://qalorie.com',
        other: '* Challenge: Editing and Trimming Videos for Sharing on Social Media\n* Design: Figma, Invision',
    },
    {
        category: 'backend',
        company: '',
        date: '',
        status: '',
        title: 'Qalorie(Calorie Measurement)',
        type: 'Node(Express.js)/MongoDB/AWS(S3 Buckets)',
        avatar: 'rafael.png',
        client: '<b>Rafael Rivera</b> (Puerto Rico)\nCEO at Qalorie, Inc.',
        role: 'Project Manager, Web, Mobile, Backend(API) Developer',
        technology: '<b>Node(Express.js)</b>, MongoDB(Database), Database Design,\nAWS S3 Buckets, SendGrid, Stripe Subscription',
        icons: [
            'node.png',
            'express.png',
            'mongodb.png',
            'aws.png',
            's3bucket.png',
            'paypal.png',
            'stripe.png',
        ],
        images: [
            { src: 'qalorie/8.png' },
            { src: 'qalorie/9.png' },
            { src: 'qalorie/0.png' },
        ],
        appstore: '',
        playstore: '',
        youtube: '',
        website: '',
        other: '',
    },
    {
        category: 'web',
        company: 'Club Mexicana',
        logo: 'club_mexicana.png',
        date: 'Sep, 2021 – Jul, 2022',
        status: 'Project Completed Successfully',
        title: 'ClubMexicana(Party Booking)',
        type: 'React(Next.js)/Node(Express.js) Website',
        avatar: 'meriel_armitage.png',
        client: '<b>Meriel Armitage</b> (United Kingdom)\nFounder & Director of Club Mexicana',
        review: {
            rating: 5,
            recommendation: "&emsp;\"Silas brought a wealth of expertise to the table. Their deep understanding of current web development trends and technologies ensured that our website was not only visually appealing but also functionally robust. They provided innovative solutions to challenges and implemented cutting-edge features that set our site apart.\""
        },
        role: 'Full-Stack Developer',
        technology: '<b>React(Next.js)</b>, Typescript, <b>Node.js(Express.js)/MongoDB</b>, DigitalOcean, Google Analytics,',
        icons: [
            'react.png',
            'next.png',
            'typescript.png',
            'node.png',
            'mongodb.png'
        ],
        images: [
            { src: 'clubmexicana/1.png' },
            { src: 'clubmexicana/2.png' },
            { src: 'clubmexicana/3.png' },
        ],
        appstore: '',
        playstore: '',
        youtube: '',
        website: 'https://www.clubmexicana.com/',
        other: '',
    },
    {
        category: 'mobile',
        company: 'Borw, Ltd.',
        logo: 'borw.webp',
        date: 'Jul, 2019 – Feb, 2020',
        status: 'Project Completed Successfully',
        title: 'Borw(Circular Fashion, Buy & Sell)',
        type: 'React Native(Android/iOS) Mobile Application',
        avatar: 'eleftheria1.jpg',
        client: '<b>Eleftheria Panagiotopoulou</b> (United Kingdom)\nCEO & Founder at Borw, Lecturer at Oxford Business College & Greenwich University, Sustainable Fashion Addict',
        review: {
            rating: 5,
            recommendation: "&emsp;\"Communication with Silas was seamless. They kept us informed about project progress, promptly addressed any queries or concerns, and actively sought feedback at every stage. This transparent and collaborative approach fostered a positive working relationship and ensured that the final product aligned perfectly with our expectations.\""
        },
        role: 'Mobile Application Developer',
        technology: '<b>React Native</b>, Redux,\nFirebase Realtime Database, Firebase Cloud Function,\nSocial Authentication(Facebook, Apple, Google, Email) using Firebase,\nSocial Media Feature(Multiple Products Posting and Comment, Like, User Following),\n<b>Payment Gateway Integration</b>(PayPal, Bank Authorization),\nMulti-Language Implement(RTL/LTR) using i18n, Localization',
        icons: [
            'reactnative.png',
            'android.png',
            'ios.png',
            'firebase.png',
            'payment.png',
            'language.png'
        ],
        images: [
            { src: 'borw/5.png' },
            { src: 'borw/2.png' },
            { src: 'borw/7.png' },
            { src: 'borw/1.png' },
            { src: 'borw/8.png' },
            { src: 'borw/4.png' },
        ],
        appstore: 'https://apps.apple.com/ca/app/borw/id1504578577',
        playstore: 'https://play.google.com/store/apps/details?id=com.borw',
        youtube: 'https://youtu.be/zFQFFhuZhcY',
        website: 'https://borw.app',
        other: '* Fashion apps often require handling and displaying images\n&emsp;&emsp;(Libraries: React Native Image, FastImage, and ImagePicker)\n* Share products with their social media accounts\n&emsp;&emsp;(Libraries: react-native-share and reacct-native-fbsdk)',
    },
    {
        category: 'web',
        company: 'Moonpig',
        logo: 'moonpig.jpg',
        date: 'Jan, 2020 – Feb, 2023',
        status: 'Project Completed Successfully',
        title: 'Moonpig(Personalized Cards Online)',
        type: 'React & Android/iOS Web & Mobile Application',
        avatar: 'peter_donlon.webp',
        client: '<b>Peter Donlon</b> (United Kingdom)\nCTO at Moonpig',
        role: 'Frontend(Web & Mobile) Developer',
        technology: '<b>React(Next.js)</b>, Styled-Components, Typescript, Node.js, Redux, Apollo, GraphQL, AWS, Google Analytics, Google Ads,\nPayment Gateway Integration, <b>Android(Java)</b>, <b>iOS(Swift)</b>',
        icons: [
            'react.png',
            'next.png',
            'typescript.png',
            'node.png',
            'apollo.jpg',
            'graphql.png',
            'android.png',
            'swift.png'
        ],
        images: [
            { src: 'moonpig/1.png' },
            { src: 'moonpig/2.png' },
            { src: 'moonpig/4.png' },
            { src: 'moonpig/3.png' },
            { src: 'moonpig/5.png' },
        ],
        appstore: 'https://apps.apple.com/us/app/moonpig-birthday-cards/id393730279',
        playstore: 'https://play.google.com/store/apps/details?id=com.commonagency.moonpig.uk',
        youtube: '',
        website: 'https://www.moonpig.com/us/',
        other: '',
    },
    {
        category: 'mobile',
        company: 'Amdocs, Ltd.',
        logo: 'amdocs.png',
        date: 'Jan, 2019 – Mar, 2019',
        status: 'Project Completed Successfully',
        title: 'GoFit(Fitness, Gym & Workout)',
        type: 'React Native(Expo) Mobile Application',
        avatar: 'rabia.jpeg',
        client: '<b>Rabia Abu Hanna</b> (Israel)\nSoftware Development Team Lead at Amdocs',
        review: {
            rating: 4,
            recommendation: "&emsp;\"From a technical perspective, Silas demonstrated a mastery of React Native. The codebase was clean, well-organized, and optimized for performance. Their expertise significantly contributed to the app's smooth functionality and responsiveness.\""
        },
        role: 'React Native Developer',
        technology: '<b>React Native(Expo)</b>, Redux,\nFirebase Firestore, Database, Firebase Cloud Function,\nScheduling using Calendar, Unity Video Embeding,\nMulti-Language Implement(<b>RTL/LTR</b>) using i18n, Localization,\nSynchronizing with Bluetooth Watch(Apple Watch, Samsung Watch),\nFirebase Authentication, OAuth, or JWT(JSON Web Tokens),\nDark & Light Theme',
        icons: [
            'reactnative.png',
            'expo.png',
            'firebase.png',
            'bluetooth.png',
            'github.png',
            'sketch.png'
        ],
        images: [
            { src: 'gofit/3.png' },
            { src: 'gofit/1.png' },
            { src: 'gofit/4.png' },
            { src: 'gofit/2.png' },
        ],
        appstore: 'https://apps.apple.com/us/app/gofit-weight-loss-walking/id1460688355',
        playstore: 'https://play.google.com/store/apps/details?id=com.m4pmedia.gofit_walking',
        youtube: 'https://youtu.be/JS75-G-qFIs',
        website: '',
        other: '* Design: Sketch\n* Project Management: Hubstaff, Github'
    },
    {
        category: 'web',
        company: 'HappyCow, Inc',
        logo: 'happycow.jpg',
        date: 'Jul, 2022 – Feb, 2023',
        status: 'Project Upgrade & Maintenance',
        title: 'HappyCow(Find Vegan Restaurants)',
        type: 'PHP(Laravel)/MySQL/Nginx',
        avatar: 'paulo_bing.png',
        client: '<b>Paulo Bing</b> (Brazil)\nSoftware Engineer of HappyCow',
        role: 'Backend(PHP/MySQL) Developer',
        technology: '<b>PHP(Laravel)/MySQL</b>, Tailwind CSS, Nginx, Google Tag Manager, Wordpress, SEO',
        icons: [
            'php.png',
            'laravel.jpeg',
            'mysql.jpg',
            'tailwind.png',
            'wordpress.png',
            'seo.png'
        ],
        images: [
            { src: 'happycow/0.png' },
            { src: 'happycow/1.png' },
            { src: 'happycow/3.png' },
            { src: 'happycow/2.png' },
            { src: 'happycow/4.png' },
        ],
        appstore: 'https://apps.apple.com/us/app/happycow-vegan-food-near-you/id435871950?at=10laz4&referrer=utm_source=happycow&utm_campaign=mobile_main',
        playstore: 'https://play.google.com/store/apps/details?id=com.hcceg.veg.compassionfree&referrer=utm_source%3Dhappycow%26utm_campaign%3Dmobile_footer',
        youtube: '',
        website: 'https://www.happycow.net/',
        other: '* Challenge: Optimizing a MySQL Database for Large Datasets',
    },
    {
        category: 'mobile',
        company: 'Crave Retail, Inc.',
        logo: 'crave.jpeg',
        date: 'May, 2020 – Mar, 2021',
        status: 'Project Completed Successfully',
        title: 'HouseSigma/Brokier(Real Estates)',
        type: 'React(Next)/React Native(Expo)/PHP(Laravel)/MySQL',
        avatar: 'amir.webp',
        client: '<b>Amirghassemi Benhnam</b> (Canada)\nCTO at Crave Retail, Inc.',
        role: 'Project Manager, Full Stack Developer',
        technology: '<b>React Native(Expo)</b>, Redux, PHP, Laravel, MySQL,\nThird Party Api Integration using Axios,\nGoogle Analytics Implement\n(Libraries: react-native-firebase/analytics)',
        icons: [
            'react.png',
            'next.png',
            'reactnative.png',
            'expo.png',
            'php.png',
            'laravel.png',
            'axios.png'
        ],
        images: [
            { src: 'brokier/1.png' },
            { src: 'brokier/2.png' },
            { src: 'brokier/3.png' },
            { src: 'brokier/4.png' },
            { src: 'brokier/5.png' },
        ],
        appstore: 'https://apps.apple.com/ca/app/housesigma-canada-real-estate/id1255490256',
        playstore: 'https://play.google.com/store/apps/details?id=com.housesigma.android&hl=en_US&gl=US',
        youtube: 'https://youtu.be/lz95cwVvB5I',
        website: 'https://housesigma.com',
        other: '* Challenge: Google Map Clustering, Google Maps Markers with extensive\n&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;positions(Libraries: react-native-maps),\n&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;MySQL Indexing, Optimizing Database\n* Design: Figma\n* Project Management: Zira, Bitbucket',
    },
    {
        category: 'mobile',
        company: 'Romanian Food & Beverage, Ltd.',
        logo: 'romania.jpeg',
        date: 'May, 2020 – Sep, 2020',
        status: 'Frontend Part Completed Successfully',
        title: 'FoodNet(Restaurant, Food Delivery, Recipe)',
        type: 'React Native/Ionic(Angular)',
        avatar: 'hossain.png',
        client: '<b>Iqbal Hossain</b> (Romania)\nCOO at Romanian Food & Beverage, Ltd.',
        role: 'Frontend(Mobile Application) Developer',
        technology: '<b>React Native</b>, Redux, Hooks, Typescript,\n<b>Third Party Api Integration for Food Recipe & Ingredients</b>,\nPush Notification using Firebase Cloud Messaging\n&emsp;(Libraries: react-native-firebase/messaging),\nMulti-Language, Multi-Payment Gateway Integration\n&emsp;(Libraries: i18n, react-localization, @stripe/stripe-react-native,\n&emsp;react-native-paypal)',
        icons: [
            'reactnative.png',
            'ionic.png',
            'angular.png',
            'firebase.png',
            'spoonacular.png',
        ],
        images: [
            { src: 'foodnet/1.png' },
            { src: 'foodnet/3.png' },
            { src: 'foodnet/2.png' },
            { src: 'foodnet/4.png' },
            { src: 'foodnet/5.png' },
            { src: 'foodnet/6.png' },
            { src: 'foodnet/7.png' },
            { src: 'foodnet/8.png' },
        ],
        appstore: 'https://apps.apple.com/us/app/food-network-kitchen/id399072152',
        playstore: 'https://play.google.com/store/apps/details?id=com.scripps.android.foodnetwork&hl=en_US',
        youtube: 'https://youtu.be/XDGSIJ3WguM',
        website: '',
        other: '* Design: Invision\n* Project Management: Hubstaff, GitLab, Slack',
    },
    {
        category: 'mobile',
        company: 'Technovier, Inc.',
        logo: 'technovier.jpeg',
        date: 'Sep, 2020 – Nov, 2020',
        status: 'Project Completed Successfully',
        title: 'Paksa/Noon(Online Shopping)',
        type: 'React Native(Android/iOS) Mobile Application',
        avatar: 'khawaja.jpeg',
        client: '<b>Khawaja Minhal Hassan</b> (Pakistan)\nCEO at Technovier, Inc.',
        role: 'Project Team Leader, Frontend Developer',
        technology: '<b>React Native</b>, Redux, Hooks, Python(Django), PostgreSQL,\nPush Notification using Firebase Cloud Messaging,\n<b>Multi-Language, Multi-Payment Gateway Integration</b>,\nProducts, Collection Management, Shopify API Integration using Axios.',
        icons: [
            'reactnative.png',
            'android.png',
            'ios.png',
            'python.png',
            'postgresql.png',
            'shopify.png',
        ],
        images: [
            { src: 'paksa/1.png' },
            { src: 'paksa/4.png' },
            { src: 'paksa/2.png' },
            { src: 'paksa/3.png' },
            { src: 'paksa/5.png' },
            { src: 'paksa/6.png' },
        ],
        appstore: 'https://apps.apple.com/us/app/noon-shopping-%D9%86%D9%88%D9%86-%D9%84%D9%84%D8%AA%D8%B3%D9%88%D9%82/id1269038866',
        playstore: 'https://play.google.com/store/apps/details?id=com.noon.buyerapp&hl=en_US&gl=US',
        youtube: 'https://youtu.be/7zK89HbPaz4',
        website: '',
        other: '* Design: XD',
    },
    {
        category: 'web',
        company: 'CoLife, Inc',
        logo: 'colife.png',
        date: 'Aug, 2020 – Apr, 2021',
        status: 'Project Completed Successfully',
        title: 'CoLife(Rent Private Room)',
        type: 'Vue(Nuxt)/Node(Express.js)/MongoDB',
        avatar: 'tom_maszk.png',
        client: '<b>Tom Maszk</b> (United States)\nCTO of CoLife, Inc',
        review: {
            rating: 5,
            recommendation: "&emsp;\"Silas possesses a solid grasp of Vue.js fundamentals. They effectively leveraged Vue components, directives, and lifecycle hooks to create modular and reusable code structures.\""
        },
        role: 'Full-Stack Developer',
        technology: '<b>Vue(Nuxt.js)</b>, Node(Express.js), MongoDB,\nGoogle Analytics, Google Tag Manager',
        icons: [
            'vue.png',
            'nuxt.png',
            'node.png',
            'express.png',
            'mongodb.png',
        ],
        images: [
            { src: 'colife/1.png' },
            { src: 'colife/6.png' },
            { src: 'colife/2.png' },
            { src: 'colife/7.png' },
            { src: 'colife/3.png' },
            { src: 'colife/8.png' },
            { src: 'colife/4.png' },
            { src: 'colife/9.png' },
            { src: 'colife/5.png' },
            { src: 'colife/10.png' },
        ],
        appstore: '',
        playstore: '',
        youtube: '',
        website: 'https://www.letscolife.com/',
        other: '',
    },
    {
        category: 'mobile',
        company: 'Hitasoft Technology Solutions P.ltd.',
        logo: 'hitasoft.jpg',
        date: 'May, 2018 – Nov, 2018',
        status: 'Project Completed Successfully',
        title: 'Howuz(Online Dating)',
        type: 'Fultter(Android/iOS) Mobile Application',
        avatar: 'raja.jpeg',
        client: '<b>Raja Hussain</b> (India)\nCTO at Hitasoft Technology Solutions P.ltd.',
        role: 'Frontend Developer',
        technology: '<b>Fultter</b>, DAT, Java(Spring Boot), Video & Voice Call,\nPush Notification using Firebase Cloud Messaging',
        icons: [
            'flutter.png',
            'dat.png',
            'java.png',
            'springboot.png',
        ], images: [
            { src: 'howuz/1.png' },
            { src: 'howuz/2.png' },
        ],
        appstore: '',
        playstore: 'https://play.google.com/store/apps/details?id=com.hitasoft.app.howzu&hl=en_US&gl=US',
        youtube: '',
        website: '',
        other: '* Design: Figma',
    },
    {
        category: 'web',
        company: 'iSono Health, Inc',
        logo: 'isono_health.png',
        date: 'May, 2018 – Jul, 2018',
        status: 'Project Completed Successfully',
        title: 'iSono Health(Say hello to atusa)',
        type: 'Wordpress Website',
        avatar: 'shadi_saberi.jpeg',
        client: '<b>Shadi Saberi</b> (United States)\nFounder, CTO of iSono Health, Inc',
        review: {
            rating: 5,
            recommendation: "&emsp;\"He demonstrated a commitment to deadlines and delivered the final product on time. This reliability allowed us to launch our website according to our planned schedule, contributing to the overall success of our online presence.\""
        },
        role: 'Full-Stack Developer',
        technology: '<b>PHP(Wordpress)</b>, Vercel',
        icons: [
            'php.png',
            'wordpress.png',
        ],
        images: [
            { src: 'isonohealth/1.png' },
            { src: 'isonohealth/2.png' },
        ],
        appstore: '',
        playstore: '',
        youtube: '',
        website: 'https://isonohealth.com/',
        other: '',
    },
];